store/config/routes.rb
Rails.application.routes.draw do
  get "products/index"
  
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products
  root 'products#index'
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

store/app/models/product.rb
class Product < ApplicationRecord
validates :name, presence: true
end

store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
end

store/app/helpers/application_helper.rb
module ApplicationHelper
end

store/app/helpers/products_helper.rb
module ProductsHelper
end

store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

store/app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>index</title>
</head>
<body>
  <h1>Products#index</h1>
<ol id="products">
  <% @products.each do |product| %>
  <li> <%= link_to product.name, product%> </li>
  

  <% end%>
</ol>
</body>
</html>

store/app/views/products/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>index</title>
</head>
<body>
  <form post='products/create', >
    <div for='name'>
      <label> Name</label>
      <input type='text'/> 
    </div>
    <div for='about'>
      <label> About</label>
      <input type='text'/> 
    </div>
    <button type='submit'> submit </button>
  </form>
</body>
</html>

store/app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>index</title>
</head>
<body>
  <p><%= Product.column_names %> </p>
  <h1>Product name <%= @product.name%> </h1>
  <h2> <%= @product.about%> </h2>
  <div> <a href=<%= products_path%>> back </a></div>
</body>
</html>